declare module '*.png'
declare module '*.svg'
declare module '*.jpeg'
declare module '*.jpg'
declare module '*.json'
declare module '*.css'
declare module '*.less'
declare module '*.gif'
declare module '*.scss'

